
version: '2'
services:
  wires:
    build:
      context: ./
    image: wire:latest
    volumes:
      - ./playground/wireframes:/opt/wireframes
      - ./playground/sites:/var/www/html
      - ~/.npm:/root/.npm
      - .:/opt/app
    ports:
      - 8100:80
      - 3300:3300
    environment:
      - WIRES_DOMAIN=wires.activelamp.local
      - WIRES_SITE_ROOT=/var/www/html
      - ENV=dev

